"""initial migrations

Revision ID: 729f773f20f8
Revises: 
Create Date: 2021-05-12 10:35:24.682911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729f773f20f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('shape', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('box_type', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_box_type'), 'product', ['box_type'], unique=False)
    op.create_index(op.f('ix_product_color'), 'product', ['color'], unique=False)
    op.create_index(op.f('ix_product_count'), 'product', ['count'], unique=False)
    op.create_index(op.f('ix_product_created_at'), 'product', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_deleted_at'), 'product', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_product_order'), 'product', ['order'], unique=False)
    op.create_index(op.f('ix_product_shape'), 'product', ['shape'], unique=False)
    op.create_index(op.f('ix_product_type'), 'product', ['type'], unique=False)
    op.create_index(op.f('ix_product_updated_at'), 'product', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_updated_at'), table_name='product')
    op.drop_index(op.f('ix_product_type'), table_name='product')
    op.drop_index(op.f('ix_product_shape'), table_name='product')
    op.drop_index(op.f('ix_product_order'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_index(op.f('ix_product_deleted_at'), table_name='product')
    op.drop_index(op.f('ix_product_created_at'), table_name='product')
    op.drop_index(op.f('ix_product_count'), table_name='product')
    op.drop_index(op.f('ix_product_color'), table_name='product')
    op.drop_index(op.f('ix_product_box_type'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
