"""initial migration

Revision ID: dc380f9e30b7
Revises: 
Create Date: 2021-05-02 13:37:30.888452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc380f9e30b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('shape', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_color'), 'product', ['color'], unique=False)
    op.create_index(op.f('ix_product_created_at'), 'product', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_deleted_at'), 'product', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_product_shape'), 'product', ['shape'], unique=False)
    op.create_index(op.f('ix_product_type'), 'product', ['type'], unique=False)
    op.create_index(op.f('ix_product_updated_at'), 'product', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_updated_at'), table_name='product')
    op.drop_index(op.f('ix_product_type'), table_name='product')
    op.drop_index(op.f('ix_product_shape'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_index(op.f('ix_product_deleted_at'), table_name='product')
    op.drop_index(op.f('ix_product_created_at'), table_name='product')
    op.drop_index(op.f('ix_product_color'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
